sudo: false
language: go

services:
  - redis-server

go:
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get gopkg.in/redis.v5
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/github.com/teambition
  - mv `pwd` $HOME/gopath/src/github.com/teambition/ratelimiter-go
