sudo: false
language: go
go:
  - 1.7
  - tip
matrix:
  allow_failures:
    - go: tip
services:
  - redis-server
install:
  - go get gopkg.in/redis.v5
  - go get github.com/stretchr/testify/assert
script: go test .
